---
# handlers file for ansible-nexus

- include: "service/{{ ansible_service_mgr }}.yml"

- name: 'start nexus'
  become: true
  service: name=nexus state=started
  tags:
    - init

- name: 'restart nexus'
  become: true
  service: name=nexus state=restarted
  notify:
    - 'wait for nexus'
  
- name: 'wait for nexus'
  wait_for: port={{nexus_port}} delay=10
