---
# handlers file for ansible-nexus

- name: 'start nexus'
  sudo: yes
  service: name=nexus state=started
  tags:
    - init

- name: 'restart nexus'
  sudo: yes
  service: name=nexus state=restarted
  notify:
    - 'wait for nexus'

- name: 'reload nexus'
  sudo: yes
  command: "systemctl daemon-reload"
  
- name: 'wait for nexus'
  wait_for: port={{nexus_port}} delay=10
