- name: Add nexus service
  template:
    src: nexus.service.j2
    dest: "/etc/systemd/system/nexus.service"
    
- name: Register nexus service at startup
  systemd:
    daemon_reload: yes
    name: nexus.service
    enabled: true
  notify:
    - 'reload systemd'

